name: load-rs::bump-dependencies

# Currently these dependencies are updated once per 1-2 months
#   but there is not an any established day to update them
# Workflow on `schedule` trigger could be run only on master/base branch
# Run workflow At 10:00 UTC on Monday and Friday every week
on:
  schedule:
    - cron: '0 10 * * 1,5'

# TODO: try to switch to workflow `dispatch` trigger and move workflows to dev and release branches
#       in the future when iroha2-dev team will agree with it

env:
  VERSION_URL: 'https://raw.githubusercontent.com/hyperledger/iroha/iroha2/data_model/Cargo.toml'

jobs:
  bump-load-rs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get iroha2 version from hyperledger repository
        uses: mathiasvr/command-output@v1
        id: new_version
        with:
          run: curl -s ${{ env.VERSION_URL }} | sed -n '3p' | sed -e 's/version = "//g' -e 's/"$//' | tr -d '\n'
      - name: Edit package.version key
        uses: ciiiii/toml-editor@1.0.0
        with:
          file: "Cargo.toml"
          key: "package.version"
          value: ${{ steps.new_version.outputs.stdout }}
      - name: Edit iroha_client.version key
        uses: ciiiii/toml-editor@1.0.0
        with:
          file: "Cargo.toml"
          key: "dependencies.iroha_client.version"
          value: ${{ steps.new_version.outputs.stdout }} 
      - name: Edit iroha_data_model key
        uses: ciiiii/toml-editor@1.0.0
        with:
          file: "Cargo.toml"
          key: "dependencies.iroha_data_model.version"
          value: ${{ steps.new_version.outputs.stdout }}
      - name: Push changes
        uses: devops-infra/action-commit-push@v0.9.0
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          add_timestamp: true
          commit_message: "bump iroha2 versions in Cargo.toml"
          target_branch: bump-iroha2-version
      - name: Get PR branch name
        uses: mathiasvr/command-output@v1
        id: pr_branch
        with:
          run: git symbolic-ref --short HEAD | tr -d '\n'
      - name: Create pull request
        uses: vsoch/pull-request-action@1.0.19
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: "master"
          PULL_REQUEST_FROM_BRANCH: "${{ steps.pr_branch.outputs.stdout }}"
          PULL_REQUEST_TITLE: "Update iroha2 dependencies to ${{ steps.new_version.outputs.stdout }}"
          PULL_REQUEST_BODY: "**Automated pull request**<br><br><p>Update `iroha client` and `iroha_data_model` dependencies from <a href=${{ env.VERSION_URL }}>Hyperledger repository</a></p>"
          PULL_REQUEST_ASSIGNEES: ${{ github.actor }}
          PULL_REQUEST_REVIEWERS: BAStos525
          PULL_REQUEST_TEAM_REVIEWERS: soramitsu/devops-team soramitsu/devops-support
          PULL_REQUEST_UPDATE: true
